language: node_js
node_js:
  - stable
git:
  depth:       3
cache: npm
install:
  - npm i -g sequelize-cli
  - npm install
directories:
  - node_modules
services:
  - mysql
before_install:
  - cd API
  - mysql -e 'CREATE DATABASE IF NOT EXISTS cinema_test;'
script:
  - npm run test-dev
after_success:
  - npm run coveralls
notifications:
  email:       false
